# 开发环境配置
app:
  prefix: '/api'
  port: 8081
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关, 开发环境
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址
    domain: 'http://www.tamasaki-group.com'
    # 文件虚拟路径, 必须以 / 开头
    serveRoot: '/static'
# 数据库配置
db:
  mysql:
    host: '160.16.152.44'
    username: 'root'
    password: 'tamasaki168168'
    database: 'kapok'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: '160.16.152.44'
  port: 6379
  db: 0
  password: 'tamasaki168168'
  keyPrefix: 'nest:'

# jwt 配置
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 权限 白名单配置
perm:
  router:
    whitelist: [ { path: '/api/register', method: 'POST'  }, { path: '/api/login', method: 'POST' }, { path: '/api/perm/{id}', method: 'GET' }, { path: '/api/oss/upload', method: 'POST' }]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'tamasaki168168'
